export const CHANGE_DEPARTMENT_AMOUNT = 'CHANGE_DEPARTMENT_AMOUNT';
export const UPDATE_SERVICE_SPENDING_AMOUNT = 'UPDATE_SERVICE_SPENDING_AMOUNT';
export const RESET_DEPARTMENT_AMOUNT = 'RESET_DEPARTMENT_AMOUNT';
